### ISSUE TITLE
[LinesCounter] Знакомый регекс

### ISSUE THREAD

**Issue by pavel-b-novikov** [KhegayIV/nsudotnet#1]
//._$|/\_._\_/| +|\t+

Я его уже видел в чьей-то задаче, равнок как и все окружающие строки. Признавайтесь - давали кому-то списывать/списывали сами?

**Comment by YulimitBreak** [comment]
Не списывал и самостоятельно списывать никому не давал. Регекс очевидный по построению - просто убираем  всё между // и концом строки (звёздочки почему-то потёрлись), затем в блоках, растянувшихся на одну строчку, затем пробелы (один или более, чтобы на нуле пробелов не спотыкаться) и символы табуляции (ну, в смысле, не затем, а вместе), и если в строке после ничего не осталось, её игнорируем. На мой взгляд, довольно очевидное решение, и не очень удивительно, что я не единственный, кому оно пришло в голову.

**Comment by pavel-b-novikov** [comment]
А насколько использование регексов для этой задачи вообще оправдано?

**Comment by YulimitBreak** [comment]
Ну, мне это показалось логичным вариантом. Берём строку, выкидываем лишнее, смотрим, осталось ли что-нибудь, и не считаем, если всё, что в ней было - это комменты и пустота.
Не смог придумать более удобной альтернативы, учитывая возможные случаи того, каким образом у нас могут сочетаться комментарии по //, по блокам /\* */ и пробелы. Например, у нас вот такая вещь
/*Текст текст*/   /*Текст текст текст
ещё /* немного /* текста*/1//И снова /*текст текст текст
Я посчитал, что парсить всё это вручную лишено смысла - лучше выкинуть ненужное, посчитать строчку с единицей и закончить с этим

**Comment by pavel-b-novikov** [comment]
Вот собсно и нет. Про быстродействие регексов вы можете что-то сказать?

**Comment by YulimitBreak** [comment]
Хм. Я предполагал, что String.Replace использует внутри регекс, поэтому лучше заранее создать и скомпилировать регекс и использовать его (что я сделал неправильно, потому что он всё равно создаётся на каждый файл, и к тому же, я не указал Compile), но сейчас поиск дал результаты, что String.Replace быстрее. Или я что-то не понимаю?

**Comment by YulimitBreak** [comment]
Хм. Или стоп. Я чего-то не понимаю. String.Replace не выглядит так, будто принимает регулярные выражения на вход.

**Comment by YulimitBreak** [comment]
Пока что я регексы вынес в поля. Сойдёт, или проблема в самом их существовании?

**Comment by pavel-b-novikov** [comment]
>  предполагал, что String.Replace использует внутри регекс
> Вы точно на ФИТе учитесь? О_о

Да проблемы с существованием регексов нет никакой. Прекрасно что вы владеете регулярными выражениями, но для данной задачи это пальба из пушки по воробьям. 

Но утверждение о том, что системный string.Replace использует регулярные выражения - это что-то с чем-то. 
Не говорите так больше не при ком.

**Comment by YulimitBreak** [comment]
Ну, ошибся, с кем не бывает. То, что string.Replace их не принимает (с чего я решил, что оно это делает - ещё более интересный вопрос, на который у меня нет ответа), убедило, что я неправ.
