### ISSUE TITLE
[TicTacToe] Пробельные строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [KhegayIV/nsudotnet#3]
> P L A Y E R    O    W I N S
> А вот вы это вручную вводили?
> Слушайте, сделайте extension-метод для строки, который будет преобразовывать любую строку в такую радость.

**Comment by YulimitBreak** [comment]
Сделано

**Comment by pavel-b-novikov** [comment]
Не складывайте классы в один файл. Ну пожалуйста.

**Comment by YulimitBreak** [comment]
Исправлено
