### ISSUE TITLE
[TicTacToe] Архитектура

### ISSUE THREAD

**Issue by pavel-b-novikov** [KhegayIV/nsudotnet#4]
Я заценил конечно подход с View-ами. Он очень адекватен и крут. 
Но есть одно "но". Вы хоть распишите как вы собираетесь эту радость потом адаптировать под WPF? А то решение получается не особо расширяемым.

**Comment by YulimitBreak** [comment]
Если быть честным, не особо думал об адаптации под WPF на момент разработки и проектирования. Даже наоборот, старался всё сделать так (именно этот подход с View), чтобы если расширять - расширять под этот консольный экран. Ну, или использовать эти наработки для других проектов

**Comment by pavel-b-novikov** [comment]
Ну так вы в любом случае столкнетесь с необходимостью переписать все к чертям, если задумаетесь заточить имеющееся под другой проект.

**Comment by YulimitBreak** [comment]
Почему же, просто взять .Display и выкинуть .Views. Экран и базовые вьюхи не зависят от остального проекта, и их вполне можно переиспользовать, просто написать новые View. Базовых View можно сделать и побольше, но сейчас это не потребовалось.

**Comment by pavel-b-novikov** [comment]
Ладно, и так сойдет.
